version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    assignees:
      - "nezaki"
