repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/PyCQA/flake8
    rev: master
    hooks:
    - id: flake8
      args:
        - "--config=setup.cfg"
